import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";

export default function Home() {
	return (
		<div className="h-screen w-full bg-[#f8f8f8] grid place-items-center">
			<Head>
				<title>Slack</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex flex-col bg-white p-[100px] text-center items-center rounded-md shadow-lg">
				<img className="object-contain h-[100px] mb-[60px]" src="https://cdn.mos.cms.futurecdn.net/SDDw7CnuoUGax6x9mTo7dd.jpg" alt="" />
				<h2>Select a channel to start chatting</h2>
			</div>
		</div>
	);
}
